on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          WEBHOOK_URL: https://api.qoddi.com/push/?key=kw3t957ye24h8ljv6ru1cfxgisqpdnzobam
        run: |
          curl -X GET https://api.qoddi.com/push/?key=kw3t957ye24h8ljv6ru1cfxgisqpdnzobam
